language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
  - mvn -P coverall clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: CC5bs+N8x34Qn489NxckLA2pjaGRXbQoChvPWP20j33tgiVc4g2CcXila8csqUPCzG6USs8C4hsIlLIKcX2U1T5zGI49juZzS/A2uqjy/bXPbQIm5T3WMhDy5W1hcsgNJuX5E/v9bOqp8rILm1c8dnfgts/pfZtwm5/AkoQMDURkUgSTBQ9RFZHG7RQhsY3Jo4WWQAuUV/h04m30Bs1/4D7qU81IPvzlSD405/EOiHdJsRnrXe6QLemojmdBxXRyUMXLqQTwRwFNVyTyAm3hIAJb9yKy9zvW4ce7+/JARaKN3qZiv98Zhr6G+onXY7hgUx3FmIeEYVdigi7WUgc9FqWcDHem7uZ/4s8FgNkcxlj7U4Fo4Y0F3QoAN/LYO4Fv5A9Pqc7r7qKIYg4CJSYZlholHK4vqui5/v1c35/usmLD0Sui7hIKIEIcqXbIKeL50gCXpP+fK+q2aeAD3LYIqSVA4uXyiCW1OWwhhcAfO2Ps4rsWFc3XcgMxBJu+yxRyFtdtbG808hksGVEWUwqm/D1DjAvi7sIk48SZoepqy8CcDtv7/Ck4ltz5sdVF/TYp1LdMdyOZ557kH3qxjK8k5sPNcv0EClnSmFPfm+k5MzGJS8LUz0dreFNbUm3NZVNO302NSnjRB+c1AzxYkR0n3tOzfg353VPm05O9Xtr0sAo=
